### ISSUE TITLE
CI优化提速的几个点

### ISSUE THREAD

**Issue by le0l1** [le0l1/learn-note#24]
### 1. 合理使用Cache
合理使用Cache, 可以大幅提升CI的运行速度，提高开发效率，再做Merge Request的时候, 动不动就20 30分钟的CI时间，着实太让人糟心了
在npm环境下使用`package-lock.json`作为Cache的key, 仅当lock文件发生改变时,才重新触发install 这样能大大减少我们重复安装依赖的时间
目前在Circle CI和Gitlab CI都有使用用md5或者其他的加密算法获取`package-lock.json`的hash值,以此作为Cache key的案例，有兴趣自行Google

下面放一段项目中使用Cache优化后的前后对比
![image](https://user-images.githubusercontent.com/20632096/103256707-2e5c7f00-49c9-11eb-92e3-56720f715663.png)
![image](https://user-images.githubusercontent.com/20632096/103256722-39afaa80-49c9-11eb-83a3-3399e196447e.png)

同样的Stage, 运行速度差不多提升了180%左右  效果很惊人 对于开发帮助极大
顺便贴一下部分Gitlab CI的配置

```yml
cache:
  key: "cache-$(sha256sum package-lock.json | awk '{print $4}')"
  paths:
    - node_modules/
    - packages/platform-new/dist/
    - packages/platform-admin/dist/
    - packages/agent/dist/
```
